### PR TITLE
[GR-30929] Add support for writing big endian data to files.

### PR DESCRIPTION
**Pull request by christianhaeubl**

### CODE REVIEW

**Review by jiekang — APPROVED** [review]
Tested with my write-uninterruptibly branch with this change:
```
diff --git a/substratevm/src/com.oracle.svm.jfr/src/com/oracle/svm/jfr/JfrChunkWriter.java b/substratevm/src/com.oracle.svm.jfr/src/com/oracle/svm/jfr/JfrChunkWriter.java
index 5bb060a7837..9f4ba52f059 100644
--- a/substratevm/src/com.oracle.svm.jfr/src/com/oracle/svm/jfr/JfrChunkWriter.java
+++ b/substratevm/src/com.oracle.svm.jfr/src/com/oracle/svm/jfr/JfrChunkWriter.java
@@ -80,7 +80,7 @@ public final class JfrChunkWriter implements JfrUnlockedChunkWriter {
 
     @Override
     public void initialize(long maxChunkSize) {
-        this.fileOperationSupport = ImageSingletons.lookup(RawFileOperationSupport.class);
+        this.fileOperationSupport = RawFileOperationSupport.bigEndian();
         this.notificationThreshold = maxChunkSize;
     }
 
```

The resulting jfr file has the expected byte ordering.

I can't really speak to the reverseBytes solution. It feels awkward since `jdk.internal.misc.Unsafe` tries to reverse into native ordering. Ideally it would support a specific ordering so we don't need to reverse twice to get what we want :P

**Review by rkennke — APPROVED** [review]
Looks good to me!

**Comment by christianhaeubl** [comment]
@jiekang: in which scenario do we reverse the bytes twice?

**Comment by jiekang** [comment]
> @jiekang: in which scenario do we reverse the bytes twice?

Hm, I think this was a mistaken assumption from me. Originally I thought:
Java values are big endian, my system is little endian and the output is little endian. The Pointer->Word->Unsafe implementation must have reversed the bytes in Unsafe in order to output little endian data. So to get big endian, we reverse it beforehand and thus there are two reverses.

However reading through Unsafe more closely, it's not so clear to me anymore for e.g. `putShort`. I see `putShortUnaligned` would do that but that isn't on the current code path. Also maybe my very first assumption of bytes being reversed to output little endian data is false.

**Comment by christianhaeubl** [comment]
Already part of https://github.com/native-image-jfr/graal/pull/23

**Pull request closed without merging**
